WebMiCay/Areas/Admin/Models/BillViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebMiCay.Areas.Admin.Models
{
    public class BillViewModel
    {
        public string MaHD { get; set; }
        public DateTime? NgayDat { get; set; }
        public decimal? TongGia { get; set; }
        public string TinhTrang { get; set; }
        public string MaNV { get; set; }
        public int SoLuongMon { get; set; }
        public string MaMon { get; set; }
        public string TenMon { get; set; }
        public decimal GiaCa { get; set; }
        public string MaTheLoai { get; set; }
        public string MaKH { get; set; }
        public string TenKH { get;set; }
        public string SDT { get; set; }
        public string MaTaiKhoanKhach { get; set; }
        public string TenTaiKhoanKhach { get;set; }

        public List<ChiTietHoaDonViewModel> ChiTietHoaDon { get; set; }
    }

    public class ChiTietHoaDonViewModel
    {
        public string MaMon { get; set; }
        public string MaHD { get; set; }
        public int? SoLuongMon { get; set; }
        public string TenMon { get; set; }
        public decimal GiaMon { get; set; }
    }
}

WebMiCay/Areas/Admin/Controllers/BillController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebMiCay.Areas.Admin.Models;

namespace WebMiCay.Areas.Admin.Controllers
{
    public class BillController : Controller
    {
        QuanLyQuanMiCayEntities db = new QuanLyQuanMiCayEntities();
        public ActionResult Index()
        {
            var data = (from a in db.HoaDon
                        join d in db.KhachHang on a.MaKH equals d.MaKH
                        join e in db.TaiKhoanKhach on d.MaKH equals e.MaKH
                        select new BillViewModel
                        {
                            MaKH = d.MaKH,
                            TenKH = d.TenKH,
                            SDT = d.SDT,
                            MaTaiKhoanKhach = e.MaTaiKhoanKhach,
                            TenTaiKhoanKhach = e.TenTaiKhoanKhach,
                            MaHD = a.MaHD,
                            NgayDat = a.NgayDat,
                            TinhTrang = a.TinhTrang,
                            TongGia = a.TongGia,
                            MaNV = a.MaNV,
                            ChiTietHoaDon = (from b in db.CTHD
                                             join c in db.Mon on b.MaMon equals c.MaMon
                                             where a.MaHD == b.MaHD
                                             select new ChiTietHoaDonViewModel
                                             {
                                                 MaMon = c.MaMon,
                                                 MaHD = a.MaHD,
                                                 SoLuongMon = b.SoLuongMon,
                                                 TenMon = c.TenMon,
                                                 GiaMon = c.GiaCa
                                             }).ToList()
                        }).ToList();
            return View(data);
        }

        public ActionResult ChitietHD(string maHD, DateTime ngayDatVe, string maKH, string tenKH, string dienThoai, string maMon, string tenMon, int soLuong, decimal giaCa, decimal tongGia)
        {
            var h = db.HoaDon.SingleOrDefault(c => c.MaHD == maHD);
            var chiTietHoaDon = (from ct in db.CTHD
                                 join mon in db.Mon on ct.MaMon equals mon.MaMon
                                 where ct.MaHD == maHD
                                 select new ChiTietHoaDonViewModel
                                 {
                                     MaMon = ct.MaMon,
                                     MaHD = ct.MaHD,
                                     SoLuongMon = ct.SoLuongMon,
                                     TenMon = mon.TenMon,
                                     GiaMon = mon.GiaCa
                                 }).ToList();

            var model = new BillViewModel
            {
                MaHD = maHD,
                NgayDat = ngayDatVe,
                MaKH = maKH,
                TenKH = tenKH,
                SDT = dienThoai,
                MaMon = maMon,
                TenMon = tenMon,
                SoLuongMon = soLuong,
                GiaCa = giaCa,
                TongGia = tongGia,
                ChiTietHoaDon = chiTietHoaDon
            };

            return View(model);
        }

        public ActionResult Deletebill(string maHD)
        {
            var h = db.HoaDon.SingleOrDefault(c => c.MaHD == maHD);

            db.HoaDon.Remove(h);
            db.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

WebMiCay/Areas/Admin/Views/Bill/ChitietHD.cshtml
@model WebMiCay.Areas.Admin.Models.BillViewModel
@{
    ViewBag.Title = "ChitietHD";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<link href="~/Areas/Admin/Assets/Client/css/material-dashboard.css" rel="stylesheet" />
<div class="page-wrapper">
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Start Page Content -->
        <!-- ============================================================== -->
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Mã Hóa Đơn: @Model.MaHD</h4>
                        <ul class="list-group">
                            <li class="list-group-item border-0 ps-0 pt-0 text-sm">
                                <strong class="text-dark">Ngày đặt về:</strong> &nbsp;
                                @Model.NgayDat
                            </li>
                            <li class="list-group-item border-0 ps-0 text-sm">
                                <strong class="text-dark">Mã khách hàng:</strong> &nbsp;
                                @Model.MaKH
                            </li>
                            <li class="list-group-item border-0 ps-0 text-sm">
                                <strong class="text-dark">Tên khách hàng:</strong> &nbsp;
                                @Model.TenKH
                            </li>
                            <li class="list-group-item border-0 ps-0 text-sm">
                                <strong class="text-dark">Số điện thoại:</strong> &nbsp;
                                @Model.SDT
                            </li>
                        </ul>

                        <i class="mr-1 font-18 mdi mdi-numeric-1-box-multiple-outline"></i>

                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>

                                        <th scope="col">Tên Món</th>
                                        <th scope="col">Số Lượng</th>
                                        <th scope="col">Giá món</th>
                                        <th scope="col">Giá tổng cho từng món</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var chiTietMon in Model.ChiTietHoaDon)
                                    {
                                        <tr>
                                            <td>@chiTietMon.TenMon</td>
                                            <td>@chiTietMon.SoLuongMon</td>
                                            <td>@chiTietMon.GiaMon</td>
                                            <td>@(chiTietMon.GiaMon * chiTietMon.SoLuongMon)</td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                        <i class="mr-1 font-18 mdi mdi-numeric-1-box-multiple-outline"></i>
                        <ul class="bxx">
                            <li class="list-group-item border-0 ps-0 pt-0 text-sm" style="font-weight: bold; color: #2a00ff">
                                <strong class="text-dark">Tổng hóa đơn:</strong> &nbsp;
                                @Model.TongGia
                            </li>
                        </ul>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<style>
    .table thead th {
        padding: 8px;
        font-weight: bold;
    }

    .list-group {
        margin-left: 20px;
    }

    .bxx {
        margin-left: 780px;
    }
</style>

WebMiCay/Areas/Admin/Views/Bill/Index.cshtml
@model List<WebMiCay.Areas.Admin.Models.BillViewModel>
@{
    QuanLyQuanMiCayEntities db = new QuanLyQuanMiCayEntities();
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<head>
    <link href="~/Areas/Admin/Assets/dist/css/style.min.css" rel="stylesheet" />
    <link href="~/Areas/Admin/Assets/dist/css/icon.css" rel="stylesheet" />
    <script src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"></script>
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
</head>
<body>
    <div class="page-wrapper">
        <div class="container-fluid">
            <!-- ============================================================== -->
            <!-- Start Page Content -->
            <!-- ============================================================== -->
            <!-- basic table -->
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="table-responsive">
                                <table id="zero_config" class="table table-striped table-bordered no-wrap">
                                    <thead>
                                        <tr>
                                            <th>Tình trạng</th>
                                            <th>Mã tài khoản khách</th>
                                            <th>Tên khách hàng</th>
                                            <th>Mã hóa đơn</th>
                                            <th>Tổng hóa đơn</th>
                                            <th>Ngày đặt</th>
                                            <th>Nhân viên duyệt</th>
                                            <th>Hành động</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model)
                                        {
                                            var employee = db.NhanVien.FirstOrDefault(e => e.MaNV == item.MaNV);
                                            <tr>
                                                <td>@item.TinhTrang</td>
                                                <td>@item.MaTaiKhoanKhach</td>
                                                <td>
                                                    <a href="javascript:void(0)" class="font-weight-medium link">@item.TenKH</a>
                                                </td>
                                                <td>@item.MaHD</td>
                                                <td><a href="javascript:void(0)" class="font-bold link">@item.TongGia</a></td>
                                                <td>@item.NgayDat</td>
                                                <td>@(employee != null ? employee.MaNV : "N/A")</td>
                                                <td class="bx-tx">
                                                    <div class="d-inline-block text-nowrap">
                                                        <button class="btn btn-sm btn-icon dropdown-toggle hide-arrow" data-bs-toggle="dropdown">
                                                            <a href="@Url.Action("ChiTietHD", "Bill", new { maHD = item.MaHD, ngayDatVe = item.NgayDat, maKH = item.MaKH, tenKH = item.TenKH, dienThoai = item.SDT, maMon = item.MaMon, tenMon = item.TenMon, soLuong = item.SoLuongMon, giaCa = item.GiaCa, tongGia = item.TongGia })">
                                                                <i class="bx bx-show"></i>
                                                            </a>
                                                        </button>
                                                        <button class="btn btn-sm btn-icon delete-record">
                                                            <a href="@Url.Action("Deletebill", "Bill", new { maHD = item.MaHD })">
                                                                <i class="bx bx-trash"></i>
                                                            </a>
                                                        </button>
                                                    </div>
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="~/Areas/Admin/Assets/assets/libs/jquery/dist/jquery.min.js"></script>
    <script src="~/Areas/Admin/Assets/assets/libs/popper.js/dist/umd/popper.min.js"></script>
    <!-- apps -->
    <!-- apps -->
    <script src="~/Areas/Admin/Assets/dist/js/app-style-switcher.js"></script>
    <script src="~/Areas/Admin/Assets/dist/js/feather.min.js"></script>
    <script src="~/Areas/Admin/Assets/assets/libs/perfect-scrollbar/dist/perfect-scrollbar.jquery.min.js"></script>
    <script src="~/Areas/Admin/Assets/dist/js/sidebarmenu.js"></script>
    <!--Custom JavaScript -->
    <script src="~/Areas/Admin/Assets/dist/js/custom.min.js"></script>
    <style>
        .text-center {
            border-radius: 5%;
        }

        .badgee {
            --bs-badge-padding-x: 0.593em;
            --bs-badge-padding-y: 0.52em;
            --bs-badge-font-size: 0.8125em;
            --bs-badge-font-weight: 500;
            --bs-badge-color: #fff;
            --bs-badge-border-radius: 0.25rem;
            display: inline-block;
            padding: var(--bs-badge-padding-y) var(--bs-badge-padding-x);
            font-size: var(--bs-badge-font-size);
            font-weight: var(--bs-badge-font-weight);
            text-align: center;
            white-space: nowrap;
            vertical-align: baseline;
            border-radius: var(--bs-badge-border-radius);
        }

        .bg-label-danger {
            background-color: #ffe0db !important;
            color: #ff3e1d !important;
        }

        .bg-label-warning {
            background-color: #fff2d6 !important;
            color: #ffab00 !important;
        }

        .bg-label-success {
            background-color: #e8fadf !important;
            color: #71dd37 !important;
        }
    </style>
</body>